[build]
  base = "" # The directory where your Flask app code is located
  publish = "" # The directory containing the deploy-ready HTML files and assets
  command = "pip install -r requirements.txt && gunicorn extractor:app"

[build.environment]
  FLASK_APP = "extractor.py"
  FLASK_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production]
  publish = "output/" # The directory for production deploys
  command = "make publish"
  environment = { NODE_VERSION = "14.15.3" }
