[build]
  command = "python hls_extractor.py"
  publish = "/"
  
[build.environment]
  FLASK_APP = "hls_extractor.py"
  FLASK_ENV = "production"

[build.base]
  command = "pip install -r requirements.txt"
