[build]
  base = "/"
  publish = "/"
  command = "python -m pip install -r requirements.txt && python -m pip install gunicorn && gunicorn extractor:app"

[build.environment]
  FLASK_APP = "extractor.py"
  FLASK_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production]
  publish = "/"
  command = "python -m pip install -r requirements.txt && python -m pip install gunicorn && gunicorn extractor:app"
  environment = {
    FLASK_ENV = "production"
  }
