[build]
  base = "" # The directory where your Flask app code is located
  publish = "" # The directory containing the deploy-ready HTML files and assets
  command = "python -m pip install gunicorn"

[build.environment]
  FLASK_APP = "extractor.py"
  FLASK_ENV = "production"
