[build]
  base = ""
  publish = ""
  command = "pip install -r requirements.txt && gunicorn extractor:app"

[build.environment]
  FLASK_APP = "extractor.py"
  FLASK_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production]
  publish = ""
  command = "pip install -r requirements.txt && gunicorn extractor:app"
  environment = {
    FLASK_ENV = "production"
  }
