[build]
  base = ""  # The directory where your Flask app code is located
  publish = ""  # The directory containing the deploy-ready HTML files and assets
  command = "gunicorn -b 0.0.0.0:8080 extractor:app"  # Use a specific port (e.g., 8080)

[build.environment]
  FLASK_APP = "extractor.py"
  FLASK_ENV = "production"
